export const TRADING_PLATFORM_URL = 'https://trade.clientbridge.in/login?platizioglobal'
export const YOUTUBE_CHANNEL_URL = 'https://www.youtube.com/@platizioglobal'
export const WHATSAPP_URL = 'https://wa.me/919289837100'
export const APP_STORE_URL = 'https://apps.apple.com/in/app/platizio-global/id6789550428'
export const PLAY_STORE_URL = 'https://play.google.com/store/apps/details?id=com.platizio.global'
